# Generated by Django 5.0.7 on 2024-08-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
