# Generated by Django 5.0.7 on 2024-08-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_comment_date_alter_image_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='registration_date',
            field=models.DateField(auto_created=True),
        ),
    ]
