# Generated by Django 5.0.7 on 2024-08-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_image_author_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(max_length=255, upload_to='images'),
        ),
    ]
